### PR TITLE
Fix critical issue could not find intellij-core.jar

### PR DESCRIPTION
**Pull request by Jefersson7**
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-touch-id'.
> Could not resolve all files for configuration ':react-native-touch-id:classpath'.
   > Could not find intellij-core.jar (com.android.tools.external.com-intellij:intellij-core:26.0.1).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/external/com-intellij/intellij-core/26.0.1/intellij-core-26.0.1.jar

### CODE REVIEW

**Comment by zibs** [comment]
Are we sure we need this?

**Comment by Jefersson7** [comment]
Yes, the google maven repositories also needs to be put in the repositories sections, because gradle is currently searching only in the jcenter repositories.

**Comment by zibs** [comment]
What version are you using? I released an update yesterday.

**Comment by Jefersson7** [comment]
I'm running the v4.1.1, but I ran again my project, and it worked.

**Pull request closed without merging**
