### PR TITLE
Fixed android release build crash

### LINKED ISSUE #19: Error Application has stopped on Android when build release
Hi,
on RN 0.30.0 I have a issue on Android when build release, my application has error "Application has stopped". 

please help me fix it and build new version. Thanks you very much!

### PR DESCRIPTION
**Pull request by Richardvanwill**
Fixes #19 
This fixes the import of the package on android. It did not import TouchID.android.js when used as a node module. 
It also fixes the android js: it now provides the same interface for feature detection as the ios version, just returning false on isSupported(), instead of throwing an error on an undefined package "warning".

### CODE REVIEW

**Comment by GantMan** [comment]
Awesome work @Richardvanwill !!!

@naoufal - I'd love to see this release.

**Comment by kiruys** [comment]
👍

**Comment by naoufal** [comment]
thanks for the PR will get it merged and published later today

**Comment by pkwak-sf** [comment]
Hi @naoufal . Are there any updates on publishing this PR? Thanks!

**Comment by naoufal** [comment]
@pkwak-sf, @kiruys, @GantMan, @Richardvanwill published to npm under `react-native-touch-id@2.0.4` 🚀   Thank you all for your patience.

**Pull request merged**
