### PR TITLE
allow fallback to passcode if touchID is not enabled, enrolled or available

### PR DESCRIPTION
**Pull request by mvayngrib**
stores keychain item accessible only with user presence (fingerprint / passcode). Technique + code taken from here: https://www.secsign.com/fingerprint-validation-as-an-alternative-to-passcodes/

### CODE REVIEW

**Comment by naoufal** [comment]
@mvayngrib Can you add a screenshot or even better a video of what this looks like?

**Comment by mvayngrib** [comment]
when touchid is available, you already know how it looks, otherwise:
touchid fallback

**Comment by naoufal** [comment]
@mvayngrib Thanks for the taking the time to make that video.

I feel like including passcode as a fallback within touch id goes beyond the scope of this module.  I can see someone needing passcode without touch id.

That said, how do you feel about publishing your implementation as a standalone module?  I would gladly include it in the example portion of the readme.

**Comment by mvayngrib** [comment]
@naoufal makes sense, i can do that

**Comment by naoufal** [comment]
@mvayngrib Super.  Ping me when you've published it and I'll pull it in to an example folder I'm working on.

I'll cc you on the PR.

:+1:

**Comment by naoufal** [comment]
Closing in favour of @mvayngrib publishing a standalone `react-native-passcode` module.

**Comment by mvayngrib** [comment]
@naoufal seems triggering passcode by itself is not easy, only as a fallback. I put my implementation [here](https://github.com/tradle/react-native-local-auth)

**Comment by naoufal** [comment]
@mvayngrib I was curious and decided to take a stab at it.  Got passcode auth to work as a standalone auth method and as a fallback to Touch ID.  

I published it here https://github.com/naoufal/react-native-passcode-auth and added it as a fallback to the [Touch ID example](https://github.com/naoufal/react-native-touch-id/blob/master/examples/TouchIDExample/index.ios.js#L43-L50).

**Comment by mvayngrib** [comment]
@naoufal yea, the problem i had when i tried `evaluatePolicy:LAPolicyDeviceOwnerAuthentication` is that it shows Touch ID when it's available, i didn't see a way of forcing it to show passcode as a primary method of authentication.

**Comment by naoufal** [comment]
I see. I don't have a Touch ID device handy at the moment, do you mind
running the passcode auth example on your device?

To see if the same problem occurs.

**Comment by mvayngrib** [comment]
@naoufal sorry, a bit slammed, will check in the next couple days

**Comment by naoufal** [comment]
No worries, checked in the simulator and you're right it popups up the Touch ID dialogue if available.  I posted a question on the Apple Developer Forums to see if there's a way to force Passcode.  If there isn't I'll reopen this PR.

**Pull request closed without merging**
