### PR TITLE
Feature/support 0.40

### PR DESCRIPTION
**Pull request by mlabrum**
Hey,

I've made the changes that RN 0.40 requires, and I've also upgraded the example project to 0.40

Thanks

### CODE REVIEW

**Comment by gcarling** [comment]
@naoufal Can you please merge this? We rely on this in our project and would really love to be able to keep using it past RN-0.40. Thank you!

**Comment by ThisIsMissEm** [comment]
Can I point you to: https://medium.com/@thisismissem/how-to-upgrade-react-native-modules-in-a-backwards-compatible-manner-a5b5c48d590c

**Comment by g3r4n** [comment]
I've make it  backwards compatible in #27

**Comment by g3r4n** [comment]
Please merge this one because It's preferable to not backwards compatible module, in order to always support the last version of RN. previous version will support RN<0.40

**Comment by g3r4n** [comment]
@mlabrum can you update the Readme with the version that support RN <0.40.0 and updste the package.json ?

**Comment by u0x01** [comment]
pleaseeeee merge this pr, we need it! @naoufal

**Comment by naoufal** [comment]
@u0x01 @g3r4n @ThisIsMissEm @gcarling @mlabrum merged and published to [npm](https://www.npmjs.com/package/react-native-touch-id) under `3.0.0`.

**Pull request merged**
