### PR TITLE
Feature/face

### LINKED ISSUE #57: Face ID Support for iOS - iPhone X
How are you planning to support Face ID?

I've just tested this module (v3.1.0) on an iPhone X and although it does work correctly (so far), it needs some additional detection around Face ID.

Ideally we should be able to present users with the correct wording when opting - for example in our  App we'll show something like 'Use Touch ID?' as an opt-in when logging in (or as a setting switch). If there was additional detection for Face ID e.g. `FaceId.isSupported()` then it presents a simple way for RN to show the user the correct option.

### PR DESCRIPTION
**Pull request by naoufal**
#### Overview
- `isSupported` now resolves to `biometryType` instead of `true`.
- `biometryType` can be `FaceID` or `TouchID`.
- Updates docs
- Adds a new example that builds with `0.50` (Will delete the other example when the Android PR is merged)
- Closes #57

#### Screen
_The CTA copy is generated based on `biometryType`_
img_0003

### CODE REVIEW

**Comment by claykohut** [comment]
any idea on the timeline for getting this merged?

**Comment by naoufal** [comment]
@claykohut not yet. We still need to review this and then it'll be part of the next make release along. 

If you're in a rush I suggest device detection to deduct if the device supports FaceID.

**Comment by ben-snaize** [comment]
@naoufal This is exactly what I'm looking for, thanks very much for the quick turnaround. As a stopgap until your next release, I am using device detection as per your above comment. Works a charm given the X is the only one with Face ID support so far...

**Comment by claykohut** [comment]
I'm using device detection for now as well.

Will this PR fix the alert saying the app was designed to support touch id / hasn't been updated to support Face ID? (see below)

636452339970337497-amex-face

**Comment by naoufal** [comment]
No, you need to add something to your .plist to get rid of that.  Apple has
documentation on how to do this.

**Comment by naoufal** [comment]
@claykohut This is what you're looking for `Privacy - Face ID Usage Description (NSFaceIDUsageDescription)`.

**Comment by zackify** [comment]
Awesome can't wait for this to be merged :)

**Comment by DiederikvandenB** [comment]
+1

**Comment by zackify** [comment]
Any reason why this isn’t merged yet?

**Comment by ravelab** [comment]
+1

**Comment by tudor-ghiorghiu** [comment]
+1

**Comment by zibs** [comment]
@naoufal Just had a chance to run through this - LGTM 👍  The example gives a unhandled promise rejection if neither Face ID/Touch ID are supported (but that's a minor issue and can be fixed later).

**Comment by zackify** [comment]
@naoufal any updates here

**Comment by DiederikvandenB** [comment]
For everyone who's waiting for this to be merged, a temporary workaround is to just reference the commit from this PR. I've added this to my composer.json:
```
"react-native-touch-id": "https://github.com/naoufal/react-native-touch-id.git#d9a96f58bd39f5a2566885057add1816416a8a7b"
```

**Comment by naoufal** [comment]
Releasing in next major release, sometime next week.

**Pull request merged**
