### PR TITLE
android version < 5 crash fixed

### PR DESCRIPTION
**Pull request by 2vm**
Fixed here. Please, review and merge to master.

### CODE REVIEW

**Comment by naoufal** [comment]
@zibs mind reviewing this PR?

**Comment by rodan-lewarx** [comment]
This fixed the problem of crashing the application for me on older android phones. Good job @2vm 👍

**Comment by zibs** [comment]
thanks @2vm I'll review this today or tomorrow!

**Comment by zibs** [comment]
@2vm LGTM 👍 

Tested by building this PR on Android 4.4 (works) and comparing against master (crashes), and still works with a Pixel 8.0.

Feel free to merge this in @naoufal.

**Comment by rodan-lewarx** [comment]
Hi, @naoufal what is the status for this? Is something more needed for merge? This fix would really help. :)

**Comment by MichielDeMey** [comment]
Tested this PR on Android 4.4 API 19 and working, was crashing before this PR.
Anything needed to merge this in master?

**Pull request merged**
