### PR TITLE
Change repository order -- fix not find intellij

### PR DESCRIPTION
**Pull request by van1985**

### CODE REVIEW

**Comment by zibs** [comment]
Does changing the jcenter import actually fix this? I'm not able to do any testing until later this week - but if a few people chime in and say that it's working and not breaking things, I can merge the PR that has this in it and make a release.

**Comment by AndriiChubariev** [comment]
please, merge this. 
This change does fix the issue.
 Right now I need to do this manually at my local dev environment but CI build is blocked.

**Comment by mulhaus1** [comment]
I just tested this locally and it does fix the issue.

**Comment by zibs** [comment]
published and released as 4.1.1

**Comment by jamesmcn1** [comment]
Thanks for the update :)

**Pull request merged**
