### PR TITLE
[ANDROID] Fixed low memory bug

### PR DESCRIPTION
**Pull request by francescosgherzi**
Fixed the bug that chrashed the module, and therefore the app, when it is launched on low memory devices, than it is paused and then resumed.

### CODE REVIEW

**Comment by yarian** [comment]
I have a few questions about this change. How do we know this is safe to do? `dismissAllowingStateLoss` is just a repackaged version of `commitAllowingStateLoss`. In this case, it will avoid the exception and crash, but the fragment commit (in this case the dialog dismissal) will be lost when in the background. In essence, wouldn't this cause the dialog to not hide when it should have been?

**Comment by zibs** [comment]
I've just merged some other fixes for Android, try running the latest master/or await for the 4.0.2 release to see if this still an issue and let me know!

**Comment by zibs** [comment]
4.0.2 is now on npm

**Comment by zibs** [comment]
4.0.5 is available now too - please re-open if this is still an issue.

**Pull request closed without merging**
