### PR TITLE
Updated gradle to 3.2.1

### PR DESCRIPTION
**Pull request by XenorPLxx**
Fixes build error described here https://github.com/react-native-community/react-native-svg/issues/868

### CODE REVIEW

**Comment by SaeedZhiany** [comment]
@XenorPLxx 

You also must change the google maven repository with `google()`, please apply it before your pull request be merged

**Comment by XenorPLxx** [comment]
@SaeedZhiany 

Ok, I've swapped those repositories.

I've tested version from my fork on current project I'm working on that uses `react-native-touch-id` and everything seems to build fine after doing `./gradlew clean`.

**Comment by SaeedZhiany** [comment]
@zibs 
yes this is an issue yet, and current gradle version is not the latest one.
what do you mean "I'm no longer using this library"? you mean that there is better library we can use or what?

**Comment by XenorPLxx** [comment]
I see that in our project we've reverted `react-native-touch-id` to use npm version (was at our fork for a while), so issue that started this MR was probably fixed in some other MR like @zibs says.

I'll close it as it doesn't seem valid in version 4.3.0 of `react-native-touch-id`.

**Pull request closed without merging**
