### PR TITLE
[iOS Only] Support Passcode Fallback Natively

### PR DESCRIPTION
**Pull request by ianoshorty**
This change simply allows iOS to use Passcode fallback if its available and needed. It does not change the behaviour of FaceID / TouchID in any other way, and only uses Passcode as a fallback. Some extended discussion is at https://github.com/naoufal/react-native-touch-id/issues/34 - which notes you may wish to enable a switch to enable / disable this - but this PR is enough for us.

Happy for it to be merged if you like.

### CODE REVIEW

**Comment by EyMaddis** [comment]
bump @naoufal

**Comment by zibs** [comment]
@naoufal This works and looks good to me. I'm okay with the native fallback, we should just add something to the readme since this might change existing user's expectations.

**Comment by zibs** [comment]
Hey, thanks for the PR @ianoshorty - I'll give it a run through this week to make sure everything checks out. Let's add that optional config option to enable this feature though, since we don't want to change existing functionality. Do you mind doing that? if not, feel free to allow edits from maintainers from this PR and I'll go in an add it.

**Comment by ianoshorty** [comment]
I wont be able to further update the PR till next week. I'd be happy to take a look then though to add the config option if its needed.

**Comment by ianoshorty** [comment]
@zibs As requested, I've added a config option `passcodeFallback`, default `false`, which when `true` will utilise keypad based passcode entry. This is documented in the readme. 

Hope thats everything!

**Comment by anandwahed** [comment]
@zibs any idea when this will be merged in master ?

**Comment by zibs** [comment]
Thanks for the bump! I just need to test it and make sure it's good to go and then will merge and release asap. I can try my darn'dest to get to on the weekend if not sooner,

**Comment by zibs** [comment]
Works! Thanks! I'm going to bump the version to 4.2.

**Comment by randomor** [comment]
Is this system passcode fallback still being presented? I'm not seeing anything on iPhone X and only saw an error in the catch callback... Would appreciate some pointers on this.

**Pull request merged**
