### PR TITLE
Respect the Android lifecycle and stop listening for finger print actions when the dialog is not in-view anymore

### PR DESCRIPTION
**Pull request by mcuelenaere**
This fixes https://github.com/naoufal/react-native-touch-id/issues/132

### CODE REVIEW

**Comment by svenlombaert** [comment]
Awesome! 👍

**Comment by CapitanRedBeard** [comment]
Hey @zibs could we merge this one in? Current build throws a fatal error when overview/multitask button on Android while the touch ID is open.

Thanks for the pr @mcuelenaere !

**Comment by zibs** [comment]
Thanks! I will get to this tonight or tomorrow and make a release if it's all good

**Comment by zibs** [comment]
@mcuelenaere Do you want to resolve these conflicts? Or check if the issue has been resolved by what's in master now - thanks!

**Comment by zibs** [comment]
I've just released 4.04 - give it a shot!

**Comment by CapitanRedBeard** [comment]
Thanks @zibs

**Pull request merged**
