### PR TITLE
Fix for devices with api level lower than 23

### PR DESCRIPTION
**Pull request by martinzangl-santexgroup**
Add support libs.
Change base **hardware** classes for **support.v4.hardware**

### CODE REVIEW

**Comment by thymikee** [comment]
Thanks for that patch! I applied it locally and was able to get my app (RN 0.55) going on older Androids. Would be nice to land it, if it works for others.
cc @naoufal

**Comment by arelstone** [comment]
I cannot get this patch to work..

#### Steps
1. created emulator with Android Lollipop (API 22)
2. Changed lib in my package.json to this the fork
3. Ran `npm i`
4. Started emulator with API 22
5 installed the app on the emulator

Did i do something wrong?

I am getting this in the log
```
--------- beginning of system
--------- beginning of main
D/ReactNative( 3617): ReactInstanceManager.ctor()
D/ReactNative( 3617): ReactInstanceManager.createReactContextInBackground()
D/ReactNative( 3617): ReactInstanceManager.recreateReactContextInBackgroundInner()
D/ReactNative( 3617): ReactInstanceManager.onJSBundleLoadedFromServer()
D/ReactNative( 3617): ReactInstanceManager.recreateReactContextInBackground()
D/ReactNative( 3617): ReactInstanceManager.runCreateReactContextOnNewThread()
D/ReactNative( 3617): ReactInstanceManager.createReactContext()
D/ReactNative( 3617): Initializing React Xplat Bridge.
D/ReactNative( 3617): Initializing React Xplat Bridge before initializeBridge
D/ReactNative( 3617): Initializing React Xplat Bridge after initializeBridge
D/ReactNative( 3617): CatalystInstanceImpl.runJSBundle()
D/ReactNative( 3617): ReactInstanceManager.setupReactContext()
D/ReactNative( 3617): CatalystInstanceImpl.initialize()
E/ReactNativeJS( 3617): Java exception in 'NativeModules'
E/ReactNativeJS( 3617): 
E/ReactNativeJS( 3617): java.lang.NoClassDefFoundError: android.hardware.fingerprint.FingerprintManager$CryptoObject
```

**Comment by thymikee** [comment]
>E/ReactNativeJS( 3617): java.lang.NoClassDefFoundError: android.hardware.fingerprint.FingerprintManager$CryptoObject

Based on this error it looks like you didn't apply the patch properly, it should state `FingerprintManagerCompat$CryptoObject` if so

**Comment by arelstone** [comment]
@thymikee yes i used master. my bad.

`isSupported` seems to fail for me. for all devices, also a galaxy s9+, i get a message that fingerprint/touch id it not supported on the device

**Comment by martinzangl-santexgroup** [comment]
the main issue is when an old android os, i.e. Samsung galaxy s5 with lollipop, doesn't have the class FingerprintManager, so the crash happens before checks if is supported. No matter if you try to check at the beginning, simply the class not exist.

**Comment by thymikee** [comment]
You're right that `isSupported` fails on some devices (at least Samsung ones). We should be good however importing the FingerprintManager class and just use it for detecting hardware on >=23 API devices. I don't have the capacity to send a fix now, but that's something already done by similar libraries, and there are resources online on how to do it. 
Is OP interested in adjusting this PR?

**Comment by zibs** [comment]
@martinzangl-santexgroup Not sure why CI is failing - but can you also explain how this differs from #123 
It sounds like this PR is related to it, are they compatible?

**Comment by martinzangl-santexgroup** [comment]
Hi @zibs, I just tested [#123](https://github.com/naoufal/react-native-touch-id/pull/123) and works fine on Samsung S5. We can close this PR

**Comment by zibs** [comment]
These fixes are released in 4.04

**Pull request closed without merging**
