### PR TITLE
Fix #65 (Android FingerprintManager not supported for API lower than 23)

### LINKED ISSUE #65: Android FingerprintManager not supported for API lower than 23
I was testing the module on a couple of devices with respectively API level 21 and 17. 
With both of the devices I could manage to install the signed release APK but the app would just crash saying "the app has stopped". 
From the Logcat in Android Studio I managed to get a stacktrace with a `java.lang.RuntimeException: Could not invoke FingerprintAuth.isSupported` error. 
I then bumped into [this](https://stackoverflow.com/a/45182594/4811744) SO answer which states that "FingerprintManager is supported in API 23 and Higher", which is confirmed [here](https://developer.android.com/reference/android/hardware/fingerprint/FingerprintManager.html).

The same APK is working on a Nexus 5X with Android version 8, so API level should be 26.

Are there any known workarounds at the moment?

### PR DESCRIPTION
**Pull request by gazaret**

### CODE REVIEW

**Comment by EyMaddis** [comment]
I can confirm that this fixes crashes on older devices, good catch!

**Comment by markrickert** [comment]
Can confirm: Fixes crash on older devices. Thanks! for the great concise solution. Can get get this merged @naoufal?

**Comment by iricketson** [comment]
@zibs is this good to merge?

**Comment by zibs** [comment]
We've addressed this in pr #123 but thanks for getting to this as well. You can test this in the latest release 4.0.3.

**Pull request closed without merging**
